[meta]
title = "Go Voice Agent Starter"
description = "Get started using Deepgram's Voice Agent with this Go demo app"
author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
useCase = "voice-agent"
language = "go"
sdk = "3.1.1"
tags = ["voice-agent", "conversational-ai", "voice-ai", "voice-bot", "go"]

[build]
command = "go mod tidy"

[post-build]
message = "Run `go run main.go` to get started."
